// swift-tools-version: 5.6

// WARNING:
// This file is auto-generated.
// Do not edit this file by hand.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "LiteraeMobile",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "LiteraeMobile",
            targets: ["AppModule"],
            bundleIdentifier: "org.literae.mobile",
            teamIdentifier: "",
            displayVersion: "1.2.0",
            bundleVersion: "3",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.blue),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ]
)
