// swift-tools-version: 5.9

// WARNING:
// This file is auto-generated.
// Do not edit this file by hand.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "LiteraeMobile",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "LiteraeMobile",
            targets: ["AppModule"],
            bundleIdentifier: "org.literae.mobile",
            teamIdentifier: "",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .book),
            accentColor: .presetColor(.brown),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .fileAccess(.userSelectedFiles, .readWrite)
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ]
)
